# Generated by Django 3.0.8 on 2020-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='Book_Date',
        ),
        migrations.RemoveField(
            model_name='trek',
            name='Trek_Date',
        ),
        migrations.RemoveField(
            model_name='trek',
            name='country',
        ),
        migrations.AddField(
            model_name='trek',
            name='Country',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='trek',
            name='Pay_ID',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='trek',
            name='kk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Adventure',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Email',
            field=models.CharField(default='Individual', max_length=120),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Last_Name',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Mob_No',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Name',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='State',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Zip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trek',
            name='paymentMethod',
            field=models.CharField(default='Individual', max_length=100),
        ),
    ]
