# Generated by Django 3.0.8 on 2020-08-01 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0002_auto_20200801_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='Trek_Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 12, 1, 21, 662431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
