# Generated by Django 3.0.8 on 2020-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0002_auto_20200729_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='Trek_Date',
        ),
    ]
