# Generated by Django 3.0.8 on 2020-08-01 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0003_trek_trek_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='Book_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
