# Generated by Django 3.0.8 on 2020-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0003_remove_trek_trek_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='Book_Date',
        ),
    ]
