# Generated by Django 3.0.8 on 2020-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0004_trek_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='None', max_length=100)),
                ('Last_Name', models.CharField(default='None', max_length=100)),
                ('Adventure', models.CharField(default='None', max_length=100)),
                ('Email', models.CharField(default='None', max_length=120)),
                ('Mob_No', models.IntegerField(default=0)),
                ('message', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='trek',
            name='Adventure',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Book_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Country',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Email',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Last_Name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Pay_ID',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='State',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='trek',
            name='paymentMethod',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
