# Generated by Django 3.0.8 on 2020-08-11 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0005_auto_20200805_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='kk',
        ),
        migrations.AlterField(
            model_name='details',
            name='Mob_No',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Mob_No',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='trek',
            name='Zip',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
