# Generated by Django 3.0.8 on 2020-08-19 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0006_auto_20200811_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='Total_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
