# Generated by Django 3.0.8 on 2020-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trek', '0007_trek_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='terms',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
